/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { UserUpdateManyWithoutItemsInput } from "./UserUpdateManyWithoutItemsInput";
import {
  ValidateNested,
  IsOptional,
  IsBoolean,
  IsString,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { ListWhereUniqueInput } from "../../list/base/ListWhereUniqueInput";
@InputType()
class ItemUpdateInput {
  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutItemsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutItemsInput, {
    nullable: true,
  })
  assignedTo?: UserUpdateManyWithoutItemsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  completed?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  details?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  due?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ListWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ListWhereUniqueInput)
  @IsOptional()
  @Field(() => ListWhereUniqueInput, {
    nullable: true,
  })
  list?: ListWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}
export { ItemUpdateInput };
