/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateHouseholdCalendarArgs } from "./CreateHouseholdCalendarArgs";
import { UpdateHouseholdCalendarArgs } from "./UpdateHouseholdCalendarArgs";
import { DeleteHouseholdCalendarArgs } from "./DeleteHouseholdCalendarArgs";
import { HouseholdCalendarFindManyArgs } from "./HouseholdCalendarFindManyArgs";
import { HouseholdCalendarFindUniqueArgs } from "./HouseholdCalendarFindUniqueArgs";
import { HouseholdCalendar } from "./HouseholdCalendar";
import { EventFindManyArgs } from "../../event/base/EventFindManyArgs";
import { Event } from "../../event/base/Event";
import { Household } from "../../household/base/Household";
import { HouseholdCalendarService } from "../householdCalendar.service";

@graphql.Resolver(() => HouseholdCalendar)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class HouseholdCalendarResolverBase {
  constructor(
    protected readonly service: HouseholdCalendarService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "HouseholdCalendar",
    action: "read",
    possession: "any",
  })
  async _householdCalendarsMeta(
    @graphql.Args() args: HouseholdCalendarFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [HouseholdCalendar])
  @nestAccessControl.UseRoles({
    resource: "HouseholdCalendar",
    action: "read",
    possession: "any",
  })
  async householdCalendars(
    @graphql.Args() args: HouseholdCalendarFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HouseholdCalendar[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "HouseholdCalendar",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => HouseholdCalendar, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "HouseholdCalendar",
    action: "read",
    possession: "own",
  })
  async householdCalendar(
    @graphql.Args() args: HouseholdCalendarFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HouseholdCalendar | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "HouseholdCalendar",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => HouseholdCalendar)
  @nestAccessControl.UseRoles({
    resource: "HouseholdCalendar",
    action: "create",
    possession: "any",
  })
  async createHouseholdCalendar(
    @graphql.Args() args: CreateHouseholdCalendarArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HouseholdCalendar> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "HouseholdCalendar",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"HouseholdCalendar"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        household: args.data.household
          ? {
              connect: args.data.household,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => HouseholdCalendar)
  @nestAccessControl.UseRoles({
    resource: "HouseholdCalendar",
    action: "update",
    possession: "any",
  })
  async updateHouseholdCalendar(
    @graphql.Args() args: UpdateHouseholdCalendarArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HouseholdCalendar | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "HouseholdCalendar",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"HouseholdCalendar"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          household: args.data.household
            ? {
                connect: args.data.household,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => HouseholdCalendar)
  @nestAccessControl.UseRoles({
    resource: "HouseholdCalendar",
    action: "delete",
    possession: "any",
  })
  async deleteHouseholdCalendar(
    @graphql.Args() args: DeleteHouseholdCalendarArgs
  ): Promise<HouseholdCalendar | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Event])
  @nestAccessControl.UseRoles({
    resource: "HouseholdCalendar",
    action: "read",
    possession: "any",
  })
  async events(
    @graphql.Parent() parent: HouseholdCalendar,
    @graphql.Args() args: EventFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Event[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Event",
    });
    const results = await this.service.findEvents(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Household, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "HouseholdCalendar",
    action: "read",
    possession: "any",
  })
  async household(
    @graphql.Parent() parent: HouseholdCalendar,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Household | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Household",
    });
    const result = await this.service.getHousehold(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
